# Generated by Django 3.1.2 on 2021-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20190324_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsmeasurement',
            name='water_level',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
