# Generated by Django 3.1.2 on 2021-07-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210717_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
